POST https://data.pdiperjuangan.id/api/auth/app
Content-Type: application/json

{
    "app_id" : "1555309664580",
    "api_secret" : "4d672ce3-e422-4d8a-86ff-fabb1808a689"
}

# CONFIG UNTUK MENU
###
POST https://data.pdiperjuangan.id/api/web/config/partai
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

#PAGES
###
POST https://data.pdiperjuangan.id/api/web/pages/multimedia
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

#SEARCH
###
POST https://data.pdiperjuangan.id/api/blog/search
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"limit" : 10,
	"keyword": "berencana"
}

# ALL BLOG DATA
###
POST https://data.pdiperjuangan.id/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"


# BLOG DATA by CATEGORY ID
###
POST https://data.pdiperjuangan.id/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"order":{"key":"id","value":"desc"} ,
	"limit" : 3,
    "where" : {"key":"blog.id_category","value":"859"} 
}

# BLOG DATA by CATEGORY CHILD ID - PAKE YANG INI -
###
POST https://data.pdiperjuangan.id/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"order":{"key":"id","value":"desc"} ,
	# "limit" : 3,
    "where" : {"key":"blog.id_category_child", "value":"28"} 
}

# QUOTES DATA
###
POST https://data.pdiperjuangan.id/api/quotes/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"id" : 3
}

# BLOG DATA by CATEGORY ID
###
POST https://data.pdiperjuangan.id/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"order":{"key":"id","value":"desc"} ,
	"limit" : 3,
    "where" : {"key":"blog.id_category","value":"43"} 
}

# BLOG CATEGORY
###
POST https://data.pdiperjuangan.id/api/blog/category
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

# FIND BLOG BY ID
###
POST https://data.pdiperjuangan.id/api/blog/find/?id=859
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

# GALLERY ALBUM
###
POST https://data.pdiperjuangan.id/api/gallery/album
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"type", "value":"image"},
	"limit" : 10
}

###
POST https://data.pdiperjuangan.id/api/gallery/data?page=2
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"type", "value":"video"},
	"limit" : 10
}



###
POST https://data.pdiperjuangan.id/api/multimedia/youtube-data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 9,
    "where" : {"key":"category","value":"wawancara"} 
}

###
POST https://data.pdiperjuangan.id/api/multimedia/youtube-find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"id" : 25
}

###
POST https://data.pdiperjuangan.id/api/partai/pengurus/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 100
}

###
POST https://data.pdiperjuangan.id/api/partai/pengurus/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"id" : 7
}

###
POST https://data.pdiperjuangan.id/api/partai/legislatif/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"order" : {"key":"id","value":"desc"},
	"limit" : 10
}


###
POST https://data.pdiperjuangan.id/api/partai/legislatif/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kYXRhLnBkaXBlcmp1YW5nYW4uaWRcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjExMDEwNzE4LCJleHAiOjE2MTEwOTcxMTgsIm5iZiI6MTYxMTAxMDcxOCwianRpIjoiNTl4ZWFXRFYwOW5USXAxUSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.bg4l_GHJus7b1Z9LtsInMZwC_8G5FmE3DMi47i39x9c"

{
	"id" : 9
}

# TRACK NOMER KTA
###
GET http://101.255.87.186/anggota/lib/mpp.api.php?nokta=32760510100111730001&key=2


# TRACK NOMER KTA
###
GET http://101.255.87.186/anggota/lib/mpp.api.php?nokta=32760510100111730001&key=2