POST https://atur.biar.pw/api/auth/app
Content-Type: application/json

{
    "app_id" : "1555309664580",
    "api_secret" : "4d672ce3-e422-4d8a-86ff-fabb1808a689"
}

# CONFIG UNTUK MENU
###
POST https://atur.biar.pw/api/web/config/berita
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"

# ALL BLOG DATA
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"


# BLOG DATA by CATEGORY ID
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"

{
	"order":{"key":"id","value":"desc"} ,
	"limit" : 3,
    "where" : {"key":"blog.id","value":"692"} 
}

# BLOG DATA by CATEGORY CHILD ID - PAKE YANG INI -
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"

{
	"order":{"key":"id","value":"desc"} ,
	# "limit" : 3,
    "where" : {"key":"blog.id_category_child","value":"234"} 
}


# BLOG DATA by CATEGORY ID
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"

{
	"order":{"key":"id","value":"desc"} ,
	"limit" : 3,
    "where" : {"key":"blog.id_category","value":"28"} 
}

# BLOG CATEGORY
###
POST https://atur.biar.pw/api/blog/category
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"

# FIND BLOG BY ID
###
POST https://atur.biar.pw/api/blog/find/?id=658
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"

# GALLERY ALBUM
###
POST https://atur.biar.pw/api/gallery/album
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"type", "value":"image"},
	"limit" : 10
}

###
POST https://atur.biar.pw/api/gallery/data?page=2
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"type", "value":"video"},
	"limit" : 10
}

###
POST https://atur.biar.pw/api/web/pages/bkbb
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAzMzQ5NTg5LCJleHAiOjE2MDM0MzU5ODksIm5iZiI6MTYwMzM0OTU4OSwianRpIjoicEVuTGJPMHJ3MjZVZkVFciIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.0rvH5DclZGyk09OsuEXh4CIpGoQzof4kHTcxbcCePfg"

###
POST https://atur.biar.pw/api/multimedia/youtube-data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 10,
    "where" : {"key":"category","value":"siaran_pers"} 
}

###
POST https://atur.biar.pw/api/multimedia/youtube-find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"id" : 2
}

###
POST https://atur.biar.pw/api/partai/pengurus/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 10
}

###
POST https://atur.biar.pw/api/partai/pengurus/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"id" : 7
}

###
POST https://atur.biar.pw/api/partai/legislatif/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"order" : {"key":"id","value":"desc"},
	"limit" : 10
}


###
POST https://atur.biar.pw/api/partai/legislatif/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"id" : 9
}

# TRACK NOMER KTA
###
GET http://101.255.87.186/anggota/lib/mpp.api.php?nokta=32760510100111730001&key=2


# TRACK NOMER KTA
###
GET http://101.255.87.186/anggota/lib/mpp.api.php?nokta=32760510100111730001&key=2