POST https://atur.biar.pw/api/auth/app
Content-Type: application/json

{
    "app_id" : "1555309664580",
    "api_secret" : "4d672ce3-e422-4d8a-86ff-fabb1808a689"
}

# CONFIG UNTUK MENU
###
POST https://atur.biar.pw/api/web/config/bkbb
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

#PAGES
###
POST https://atur.biar.pw/api/web/pages/berita
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

#SEARCH
###
POST https://atur.biar.pw/api/blog/search
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"limit" : 10,
	"keyword": "berencana"
}

# ALL BLOG DATA
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"


# BLOG DATA by CATEGORY ID
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"order":{"key":"id","value":"desc"} ,
	"limit" : 3,
    "where" : {"key":"blog.id_category","value":"859"} 
}

# BLOG DATA by CATEGORY CHILD ID - PAKE YANG INI -
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"order":{"key":"id","value":"desc"} ,
	# "limit" : 3,
    "where" : {"key":"blog.id_category_child", "value":"28"} 
}


# BLOG DATA by CATEGORY ID
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"order":{"key":"id","value":"desc"} ,
	"limit" : 3,
    "where" : {"key":"blog.id_category","value":"43"} 
}

# BLOG CATEGORY
###
POST https://atur.biar.pw/api/blog/category
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

# FIND BLOG BY ID
###
POST https://atur.biar.pw/api/blog/find/?id=859
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

# GALLERY ALBUM
###
POST https://atur.biar.pw/api/gallery/album
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"type", "value":"image"},
	"limit" : 10
}

###
POST https://atur.biar.pw/api/gallery/data?page=2
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"type", "value":"video"},
	"limit" : 10
}



###
POST https://atur.biar.pw/api/multimedia/youtube-data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 9,
    "where" : {"key":"category","value":"wawancara"} 
}

###
POST https://atur.biar.pw/api/multimedia/youtube-find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"id" : 25
}

###
POST https://atur.biar.pw/api/partai/pengurus/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 100
}

###
POST https://atur.biar.pw/api/partai/pengurus/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"id" : 7
}

###
POST https://atur.biar.pw/api/partai/legislatif/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"order" : {"key":"id","value":"desc"},
	"limit" : 10
}


###
POST https://atur.biar.pw/api/partai/legislatif/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA0MDYyNjk2LCJleHAiOjE2MDQxNDkwOTYsIm5iZiI6MTYwNDA2MjY5NiwianRpIjoibUlFYUpxemN5ZGp6cGd5MCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.U1txBroYPO4G2mvCiBFn634dhtsoPPJk3XvjyM5AorE"

{
	"id" : 9
}

# TRACK NOMER KTA
###
GET http://101.255.87.186/anggota/lib/mpp.api.php?nokta=32760510100111730001&key=2


# TRACK NOMER KTA
###
GET http://101.255.87.186/anggota/lib/mpp.api.php?nokta=32760510100111730001&key=2