POST https://atur.biar.pw/api/auth/app
Content-Type: application/json

{
    "app_id" : "1555309664580",
    "api_secret" : "4d672ce3-e422-4d8a-86ff-fabb1808a689"
}

# CONFIG UNTUK MENU
###
POST https://atur.biar.pw/api/web/config
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAyMjI4MTk5LCJleHAiOjE2MDIzMTQ1OTksIm5iZiI6MTYwMjIyODE5OSwianRpIjoieHBmdEsxTkNZQUtsUThGQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.rcfa2wPQJN3280zmq0Mc1hfnMiUX8x2tCwTyiNxcn9E"

# ALL BLOG DATA
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAyMjI4MTk5LCJleHAiOjE2MDIzMTQ1OTksIm5iZiI6MTYwMjIyODE5OSwianRpIjoieHBmdEsxTkNZQUtsUThGQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.rcfa2wPQJN3280zmq0Mc1hfnMiUX8x2tCwTyiNxcn9E"

{
	"order":{"key":"id","value":"desc"} ,
	"limit" : 3,
    "where" : {"key":"blog.id_category","value":"44"} 
}

# BLOG CATEGORY
###
POST https://atur.biar.pw/api/blog/category
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAyMjI4MTk5LCJleHAiOjE2MDIzMTQ1OTksIm5iZiI6MTYwMjIyODE5OSwianRpIjoieHBmdEsxTkNZQUtsUThGQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.rcfa2wPQJN3280zmq0Mc1hfnMiUX8x2tCwTyiNxcn9E"

# FIND BLOG BY ID
###
POST https://atur.biar.pw/api/blog/find/?id=658
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAyMjI4MTk5LCJleHAiOjE2MDIzMTQ1OTksIm5iZiI6MTYwMjIyODE5OSwianRpIjoieHBmdEsxTkNZQUtsUThGQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.rcfa2wPQJN3280zmq0Mc1hfnMiUX8x2tCwTyiNxcn9E"

# GALLERY ALBUM
###
POST https://atur.biar.pw/api/gallery/album
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAyMjI4MTk5LCJleHAiOjE2MDIzMTQ1OTksIm5iZiI6MTYwMjIyODE5OSwianRpIjoieHBmdEsxTkNZQUtsUThGQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.rcfa2wPQJN3280zmq0Mc1hfnMiUX8x2tCwTyiNxcn9E"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"type", "value":"image"},
	"limit" : 10
}

###
POST https://atur.biar.pw/api/gallery/data?page=2
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAyMjI4MTk5LCJleHAiOjE2MDIzMTQ1OTksIm5iZiI6MTYwMjIyODE5OSwianRpIjoieHBmdEsxTkNZQUtsUThGQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.rcfa2wPQJN3280zmq0Mc1hfnMiUX8x2tCwTyiNxcn9E"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"type", "value":"video"},
	"limit" : 10
}

###
POST https://atur.biar.pw/api/web/pages/bkbb
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAyMjI4MTk5LCJleHAiOjE2MDIzMTQ1OTksIm5iZiI6MTYwMjIyODE5OSwianRpIjoieHBmdEsxTkNZQUtsUThGQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.rcfa2wPQJN3280zmq0Mc1hfnMiUX8x2tCwTyiNxcn9E"

###
POST https://atur.biar.pw/api/multimedia/youtube-data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 10,
    "where" : {"key":"category","value":"siaran_pers"} 
}

###
POST https://atur.biar.pw/api/multimedia/youtube-find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"id" : 2
}

###
POST https://atur.biar.pw/api/partai/pengurus/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 10
}

###
POST https://atur.biar.pw/api/partai/pengurus/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"id" : 7
}

###
POST https://atur.biar.pw/api/partai/legislatif/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"order" : {"key":"id","value":"desc"},
	"limit" : 10
}


###
POST https://atur.biar.pw/api/partai/legislatif/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjAxNzI1ODk0LCJleHAiOjE2MDE4MTIyOTQsIm5iZiI6MTYwMTcyNTg5NCwianRpIjoid0ZhYzRjV2I4ODFpOUtlQSIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.EC_AbVqtnqtsqvjLV6leOymxL8Kc7p4VEH2muKcwV_4"

{
	"id" : 9
}

