###
POST https://atur.biar.pw/api/auth/app
Content-Type: application/json

{
    "app_id" : "1555309664580",
    "api_secret" : "4d672ce3-e422-4d8a-86ff-fabb1808a689"
}

# CONFIG UNTUK MENU
###
POST https://atur.biar.pw/api/web/config/partai
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

#PAGES
###
POST https://atur.biar.pw/api/web/pages/pemilu
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

#QUOTES
###
POST https://atur.biar.pw/api/quotes/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

#QUOTES
###
POST https://atur.biar.pw/api/quotes/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"id" : 3
}

#SEARCH
###
POST https://atur.biar.pw/api/blog/search?page=1
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"limit" : 10,
	"keyword": "soekarno"
}

# ALL BLOG DATA
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"


# BLOG DATA by CATEGORY ID
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order":{"key":"id","value":"desc"} ,
	"limit" : 3,
    "where" : {"key":"blog.id_category","value":"46"} 
}

# BLOG DATA by CATEGORY CHILD ID - PAKE YANG INI -
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order":{"key":"id","value":"desc"} ,
	# "limit" : 3,
    "where" : {"key":"blog.id_category_child", "value":"262"} 
}


# BLOG DATA by CATEGORY ID
###
POST https://atur.biar.pw/api/blog/data/
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order":{"key":"id","value":"desc"} ,
	"limit" : 100,
    "where" : {"key":"blog.id_category","value":"44"} 
}

# BLOG CATEGORY
###
POST https://atur.biar.pw/api/blog/category
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

# FIND BLOG BY ID
###
POST https://atur.biar.pw/api/blog/find/?id=946
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

# GALLERY ALBUM
###
POST https://atur.biar.pw/api/gallery/album?page=1
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"type", "value":"image"},
	"limit" : 9
}

#SEARCH BY ID
###
POST https://atur.biar.pw/api/gallery/data?page=1
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"id_album", "value":"187"},
	"limit" : 22
}

# FIND GALERY BY ALBUM ID
###
POST https://atur.biar.pw/api/gallery/data?page=1
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order":{"key":"id","value":"desc"} ,
	"where":{"key":"description", "value":"Tehno Park Solo"},
	"limit" : 35
}



###
POST https://atur.biar.pw/api/multimedia/youtube-data?page=1
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 9,
    "where" : {"key":"status","value":"enable"} 
}

###
POST https://atur.biar.pw/api/multimedia/youtube-find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"id" : 28
}

###
POST https://atur.biar.pw/api/partai/pengurus/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 100
}

###
POST https://atur.biar.pw/api/partai/pengurus/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"id" : 7
}

###
POST https://atur.biar.pw/api/partai/legislatif/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order" : {"key":"id","value":"desc"},
	"limit" : 10
}


###
POST https://atur.biar.pw/api/partai/legislatif/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"id" : 9
}

###
POST https://atur.biar.pw/api/partai/dpd/data
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order" : {"key":"id","value":"desc"} ,
	"limit" : 100,
    "where" : {"key":"dpd.id_propinsi","value":"11"} 
}

###
POST https://atur.biar.pw/api/partai/dpd/data?page=4
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	"order" : {"key":"id","value":"desc"} ,
}

###
POST https://atur.biar.pw/api/partai/dpd/find
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hdHVyLmJpYXIucHdcL2FwaVwvYXV0aFwvYXBwIiwiaWF0IjoxNjA3NDkzODk2LCJleHAiOjE2MDc1ODAyOTYsIm5iZiI6MTYwNzQ5Mzg5NiwianRpIjoiMjMyeHpIV2RLWnAwRjNTUCIsInN1YiI6MTQsInBydiI6IjhmZjYzMGEwMGNhNGEzZWFmNmYyNTRmNWFiZTVhYjFiZWVkMjcyNDkifQ.NI_JR_8WiP7c02C43thBIHEOwN5AmQNlETqV1y4ze2M"

{
	
	"id" : 4

}

# TRACK NOMER KTA
###
GET http://101.255.87.186/anggota/lib/mpp.api.php?nokta=32760510100111730001&key=2


# TRACK NOMER KTA
###
GET http://101.255.87.186/anggota/lib/mpp.api.php?nokta=32760510100111730001&key=2